config/routes.rb
Guestbook::Application.routes.draw do

  root :to => 'posts#index'
  resources :posts
  resources :users
  resources :sessions
  resources :password_resets, :only => [:new, :create, :edit, :update]

  get 'feed', :to => 'posts#index', :format => 'atom', :as => 'feed'
  get 'signup', :to => 'users#new', :as => 'signup'
  get 'login', :to => 'sessions#new', :as => 'login'
  get 'logout', :to => 'sessions#destroy', :as => 'logout'
  get 'pwdreset', :to => 'password_resets#new', :as => 'pwdreset'

end

app/controllers/password_resets_controller.rb
# -*- encoding: utf-8 -*-
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => "Вам отправлено электронное письмо с дальнейшими указаниями."
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Ссылка сброса пароля просрочена."
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Пароль успешно сброшен."
    else
      render :edit
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Сброс пароля</h1>
<hr />
<%= link_to 'Начало', root_path %>
<hr />

<div id="password-reset-form-box">
  <%= form_for @user, :url => password_reset_path(params[:id]), :html => {:id => "password-reset-form"} do |f| %>
    <%= render 'shared/error_messages', :target => @user %>
    <div class="form-fields">
      <div class="form-item form-item-text form-item-password">
        <%= f.label :password, 'Новый пароль' %>
        <%= f.password_field :password, :class => 'form-text' %>
      </div>
      <div class="form-item form-item-text form-item-password">
        <%= f.label :password_confirmation, 'Подтверждение нового пароля' %>
        <%= f.password_field :password_confirmation, :class => 'form-text' %>
      </div>
      <div class="form-actions">
        <%= f.submit "Обновить пароль" %>
      </div>
    </div>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<h1>Восстановление пароля</h1>
<hr />
<%= link_to 'Начало', root_path %>
<hr />

<div id="password-reset-req-form-box">
  <%= form_tag password_resets_path, :method => :post, :id => "password-reset-req-form" do %>
    <div class="form-fields">
      <div class="form-item form-item-text form-item-email">
        <%= label_tag :email, 'Ваш eMail' %>
        <%= text_field_tag :email, params[:email], :class => 'form-text' %>
      </div>
      <div class="form-actions">
        <%= submit_tag "Сбросить пароль" %>
      </div>
    </div>
  <% end %>
</div>