config/routes.rb
Guestbook::Application.routes.draw do

  root :to => 'posts#index'
  resources :posts
  resources :users
  resources :sessions
  resources :password_resets, :only => [:new, :create, :edit, :update]

  get 'feed', :to => 'posts#index', :format => 'atom', :as => 'feed'
  get 'signup', :to => 'users#new', :as => 'signup'
  get 'login', :to => 'sessions#new', :as => 'login'
  get 'logout', :to => 'sessions#destroy', :as => 'logout'
  get 'pwdreset', :to => 'password_resets#new', :as => 'pwdreset'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  attr_accessible :content, :email, :username, :approved, :private

  validates :username, :content, :email, :presence => true
  validates :username, :length => { :minimum => 3 }
  validates :email, :email_format => true

  scope :published, where(:approved => true)
  scope :open, where(:approved => true, :private => false)

  def self.search(search)
    if search
      where('content ILIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  def self.last_post_for_email(email)
    unscoped.select("username").where("email = ?", email).last
  end

  # Публикует
  def publish
    self.approved = true
  end

  # Снимает с публикации
  def unpublish
    self.approved = false
  end

  # Возвращает признак публикации
  def published?
    self.approved
  end
end

app/controllers/posts_controller.rb
# -*- encoding: utf-8 -*-
class PostsController < ApplicationController

  # GET /posts
  # GET /posts.json
  def index
    if logged_in? && current_user.admin?
      @posts = Post.search(params[:search]).order("created_at DESC").page(params[:page]).per_page(10)
    elsif logged_in?
      @posts = Post.published.search(params[:search]).order("created_at DESC").page(params[:page]).per_page(10)
    else
      @posts = Post.open.search(params[:search]).order("created_at DESC").page(params[:page]).per_page(10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.atom
      #format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = current_resource

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    if logged_in?
      last_post = Post.last_post_for_email(current_user.email)
      if last_post
        @post.username = last_post.username
      end
    end

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = current_resource
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    if logged_in?
      @post.email = current_user.email
      @post.user_id = current_user.id
    end

    respond_to do |format|
      if ( logged_in? || verify_recaptcha(:model => @post)) && @post.save
        format.html { redirect_to posts_path, :notice => success_message(@post) }
        #format.json { render :json => @post, :status => :created, :location => @post }
      else
        flash.clear
        format.html { render :action => "new" }
        #format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = current_resource

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Сообщение успешно обновлено.' }
        #format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        #format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = current_resource
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      #format.json { head :no_content }
    end
  end

private

  def current_resource
    @current_resource ||= Post.find(params[:id]) if params[:id]
  end

  def success_message(post)
    if post.approved?
      'Сообщение успешно опубликовано'
    else
      'Сообщение будет опубликовано после проверки'
    end
  end

end

app/helpers/post_helper.rb
module PostHelper
  def markdown(text, without_follow = false)
    if without_follow
      markdown = Redcarpet::Markdown.new(ApplicationHelper::MHTMLwithoutFollow)
    else
      markdown = Redcarpet::Markdown.new(ApplicationHelper::MHTML)
    end
    return markdown.render(text).html_safe
  end

  def post_css_classes(post, classes = [])
    if !post.approved?
      classes.push 'not-approved'
    end
    if post.private?
      classes.push 'private'
    end
    classes
  end
end

app/views/posts/_form.html.erb
<div id="guestbook-form-box">
  <%= form_for @post, :html => {:id => "guestbook-form"} do |f| %>
    <%= render 'shared/error_messages', :target => @post %>

    <div class="form-fields">
      <!-- Username -->
      <div class="form-item form-item-text form-item-username">
        <%= f.label :username, "Имя" %><%= mark_required(@post, :username) %>
        <%= f.text_field :username, :size => 20, :id => 'guestbook-post-username', :class => 'form-text' %>
      </div>
      <!-- EMail -->
      <% unless logged_in? %>
        <div class="form-item form-item-text form-item-email">
          <%= f.label :email, 'eMail' %><%= mark_required(@post, :email) %>
          <%= f.email_field :email, :size => 20, :id => 'guestbook-post-email', :class => 'form-text' %>
        </div>
      <% end %>
      <!-- Content -->
      <div class="form-item form-item-textarea form-item-content">
        <%= f.label :content, 'Сообщение' %><%= mark_required(@post, :content) %>
        <%= f.text_area :content, :cols => '50', :rows => '10', :id => 'guestbook-post-content', :class => 'form-textarea' %><br />
      </div>
      <% if logged_in? %>
        <div id="post-options">
          <% if allow_param? :post, :approved %>
            <%= f.label :approved, 'Опубликован' %> <%= f.check_box :approved, {:checked => (if controller.action_name == 'new' then true else @post.approved end)} %>
          <% end %>
          <% if allow_param? :post, :private %>
            <%= f.label :private, 'Скрытый' %> <%= f.check_box :private %>
          <% end %>
        </div>
      <% end %>
      <!-- Actions -->
      <div class="form-actions">
        <%= f.submit :id => 'guestbook-form-submin', :class => 'form-submit' %>
      </div>
    </div>

    <div class="form-captcha">
      <div class="form-tips">
        При написании сообщения можно использовать разметку <%= link_to 'MARKDOWN', 'javascript:void(0)', :id => 'markdown-example-link' %>.
      </div>
      <%= content_tag :div, :id => "markdown-examples", :class => lambda{ 'element-hidden' unless logged_in?  }.call do %>
        <table>
          <thead>
            <tr>
              <th>Пример</th>
              <th>Результат</th>
            </tr>
          </thead>
          <tbody>
          <tr>
            <td>**Bold**</td>
            <td><strong>Bold</strong></td>
          </tr>
          <tr>
            <td>[Link](http://www.example.net)</td>
            <td><a href="http://www.example.net">Link</a></td>
          </tr>
          <tr>
            <td>*Italic*</td>
            <td><em>Italic</em></td>
          </tr>
          <tr>
            <td>* Listed <br />* Items</td>
            <td><ul>
              <li>Listed</li>
              <li>Items</li>
            </ul></td>
          </tr>
          <tr>
            <td>> Цитата</td>
            <td><blockquote>Цитата</blockquote></td>
          </tr>
          </tbody>
        </table>
      <% end %>
      <hr />
      <br />
      <% unless logged_in? %>
        <%= recaptcha_tags %>
      <% end %>
    </div>
    <div class="divider-left"></div>

  <% end %>
</div>

app/views/posts/_post.html.erb
<%= content_tag :div, :id => "guestbook-post-#{post.id}", :class => post_css_classes(post, ['guestbook-post', cycle("even", "odd")]) do %>
  <div class="post-meta">
    <div class="post-autor"><%= post.username %></div>
    <div class="post-time"><%=l post.created_at, :format => '%d-%m-%Y %H:%M:%S' %></div>
  </div>
  <div class="post-actions">
    <ul class="actions">
      <li><%= link_to "#", post, :class => "guestbook-post-link" %></li>
      <% if allow? :posts, :edit, post %>
      <li> | <%= link_to 'Править', edit_post_path(post), :class => ['guestbook-post-link', 'action'], :data => {'action' => 'edit', 'key' => post.id}  %></li>
      <% end %>
      <% if allow? :posts, :destroy, post %>
      <li> | <%= link_to 'Удалить', post_path(post), :method => :delete, :class => ['guestbook-post-link', 'action'], :data => {'action' => 'edit', 'key' => post.id, :confirm => 'Вы уверены?' }  %></li>
      <% end %>
    </ul>
  </div>
  <div class="post-content"><%= check_markup(markdown post.content, true) %></div>
  <div class="divider-right"></div>
<% end %>

app/views/posts/edit.html.erb
<h1>Гостевая книга</h1>
<hr />
<%= link_to 'Начало', root_path %> | <%= link_to 'Сообщение', @post %>
<hr />
<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :head, auto_discovery_link_tag(:atom, feed_path) %>
<%= link_to image_tag('feed-icon-28x28.png'), feed_path, :id => 'feed-icon' %>
<h1>Гостевая книга</h1>
<hr />
  <%= link_to 'Начало', root_path %>
   | <%= link_to 'Разместить сообщение', new_post_path %>
<hr />
<%= form_tag posts_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search], :size => 50%> <%= submit_tag 'Поиск', :name => nil %>
<% end %>
<hr />
<%= will_paginate @posts %>
<section id="guestbook">
  <hr />
  <%= render @posts %>
</section>
<hr />
<%= will_paginate @posts %>

app/views/posts/index.js.erb
$('#guestbook').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove()
<% end %>

app/views/posts/new.html.erb
<h1>Гостевая книга</h1>
<hr />
<%= link_to 'Начало', root_path %>
<hr />
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Гостевая книга</h1>
<hr />
<%= link_to 'Начало', posts_path %>
<hr />
<%= render @post %>