config/routes.rb
Guestbook::Application.routes.draw do

  root :to => 'posts#index'
  resources :posts
  resources :users
  resources :sessions
  resources :password_resets, :only => [:new, :create, :edit, :update]

  get 'feed', :to => 'posts#index', :format => 'atom', :as => 'feed'
  get 'signup', :to => 'users#new', :as => 'signup'
  get 'login', :to => 'sessions#new', :as => 'login'
  get 'logout', :to => 'sessions#destroy', :as => 'logout'
  get 'pwdreset', :to => 'password_resets#new', :as => 'pwdreset'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guestbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>

<div id="main">
  <header>
    <div id="user-header">
      <ul id="user-links">
        <% if logged_in? %>
          <li class="auth-id"><%= current_user.email %></li> | 
          <li><%= link_to "Выход", logout_path %></li>
        <% else %>          
           <li><%= link_to_unless_current "Регистрация", signup_path %></li>
           | <li><%= link_to_unless_current "Вход", login_path %></li>
        <% end %>
      </ul>
    </div>
    <div class="divider-right"></div>
  </header>
  <% if !flash.empty? %>
    <div id="flashes">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>